version: '3.5'

services:
    deluge:
        container_name: deluge
        image: linuxserver/deluge:latest
        restart: always
        environment:
            - PUID=0
            - PGID=0
        volumes:
            - /srv/deluge/downloads:/downloads
            - /srv/deluge/config:/config
            - /etc/localtime:/etc/localtime:ro
        expose:
            - "8112"
            - "58846"
        ports:
            - "7000-7009:7000-7009"
