version: '3.5'

services:
    deluge:
        # 12/06/2019
        image: linuxserver/deluge:2.0.2-0201906082034ubuntu18.04.1-ls24
        environment:
            - PUID=0
            - PGID=0
        volumes:
            - /srv/deluge/downloads:/downloads
            - /srv/deluge/config:/config
            - /etc/localtime:/etc/localtime:ro
        networks:
            - dmz

networks:
    dmz:
        external: true