version: '3.5'
services:
    emby:
        # 12/06/2019
        image: emby/embyserver:4.2.0.15
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /srv/emby/config:/config
            - /srv/tvshow:/media/tvshow
            - /srv/movie:/media/movie
        environment:
            - VIRTUAL_PORT=8096
            - VIRTUAL_HOST=emby.htpc
            - AUTO_UPDATES_ON=true
            - APP_UID=1000
            - APP_GID=1000
        networks:
            - dmz
        deploy:
            mode: replicated
            replicas: 1

    # plex:
    #         #image: plexinc/pms-docker
    #     image: linuxserver/plex

    #     environment:
    #         - PUID=1000
    #         - PGID=1000
    #         - VERSION=docker
    #     volumes:
    #         - /srv/plex/config:/config
    #         - /srv/plex/transcode:/transcode
    #         - /srv/tvshow:/data/tvshow
    #         - /srv/movie:/data/movie
    #     ports:
    #         - 32469:32469
    #         - 32400:32400
    #         - 32401:32401
    #         - 3005:3005
    #         - 8324:8324
    #         - 1900:1900/udp
    #         - 32410:32410/udp
    #         - 32412:32412/udp
    #         - 32413:32413/udp
    #         - 32414:32414/udp
    #     networks:
    #         - plex
    #         - dmz
    #     deploy:
    #         mode: replicated
    #         replicas: 1

networks:
    dmz:
        external: true

    plex:
        driver: overlay
        external: true
