version: '3.5'
services:
    emby:
      container_name: emby
      image: emby/embyserver
      restart: always
      ports:
          - 8096:8096
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - /srv/emby/config:/config
          - /srv/tvshow:/media/tvshow
          - /srv/movie:/media/movie
      environment:
          - VIRTUAL_PORT=8096
          - VIRTUAL_HOST=emby.htpc
          - AUTO_UPDATES_ON=true
          - APP_UID=1000
          - APP_GID=1000