version: '3.5'

services:
    filebrowser:
        image: filebrowser/filebrowser:v2.0.12
        volumes:
          - /srv/filebrowser/config.json:/config.json
          - /srv:/srv
          # reset database file
          # - /srv/filebrowser/database.db:/etc/database.db
        networks:
            - dmz
        deploy:
            mode: replicated
            replicas: 1

networks:
    dmz:
        external: true