version: '3.5'

services:
    filebrowser:
        image: filebrowser/filebrowser:latest
        volumes:
          - /srv/filebrowser/config.json:/config.json
          - /srv:/srv
          - /srv/filebrowser/database.db:/etc/database.db