version: '3'

services:
  jupyter:
    #04/08/2019
    image: jupyter/datascience-notebook:58169ec3cfd3
    networks:
      - dmz
    ports:
      - "8888:8888"
    volumes:
      - /srv/jupyter/work:/home/jovyan/work
    # environment:
    #   - CONDA_ENVS_PATH=${REPO_HOME}/envs

networks:
  dmz:
    external: true