version: '3.5'

services:
    radarr:
        container_name: radarr
        image: linuxserver/radarr
        restart: always
        expose:
            - "7878"
        ports:
            - "7878:7878"
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /srv/deluge/downloads:/downloads:rw
            - /srv/radarr/config:/config:rw
            - /srv/movie:/movies
            - /etc/localtime:/etc/localtime:ro
        links:
            - deluge

        depends_on:
            - deluge