version: '3.5'

services:
    radarr:
        # 19/06/2019
        image: linuxserver/radarr:2.0.0.1358-kncjawur-ls7
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /srv/deluge/downloads:/downloads:rw
            - /srv/radarr/config:/config:rw
            - /srv/movie:/movies
            - /etc/localtime:/etc/localtime:ro
        networks:
            - dmz
        deploy:
            mode: replicated
            replicas: 1

networks:
    dmz:
        external: true