version: '3'

services:
    db:
        image: postgres:11.2
        environment:
            - MYSQL_DATABASE=${MARIA_DB}
            - MYSQL_USER=${MARIA_USER}
            - MYSQL_PASSWORD=${MARIA_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MARIA_ROOT_PASSWORD}
        expose:
            - "3306"
        volumes:
            - /srv/mariadb:/var/lib/mysql

    nextcloud:
        container_name: nextcloud
        image: nextcloud:latest
        restart: always
        expose:
            - "80"
        volumes:
            - /srv/nextcloud:/var/www/html
        links:
            - mariadb
        depends_on:
            - mariadb