version: '3'

services:
    db:
        image: postgres:11.2
        environment:
            - POSTGRES_USER=nextcloud
            - POSTGRES_PASSWORD=nextcloud
            - POSTGRES_DB=dont_care
        volumes:
            - /srv/temp/postgres:/var/lib/postgresql/data
        networks:
            - nextcloud
        deploy:
            mode: replicated
            replicas: 1

    nextcloud:
        image: nextcloud
        depends_on:
            - db
        environment:
            - POSTGRES_DB=nextcloud
            - POSTGRES_USER=nextcloud
            - POSTGRES_PASSWORD=nextcloud
            - POSTGRES_HOST=db
        volumes:
            - /srv/temp/nextcloud:/var/www/html
        networks:
            - dmz
            - nextcloud
        deploy:
            mode: replicated
            replicas: 1
            placement:
                constraints: [node.role == manager]

networks:
  dmz:
    external: true
  nextcloud:
    driver: overlay
