version: '3.5'

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: always
    environment:
      TZ: Europe/Paris
      ADVERTISE_IP: https://plex.vincentriouallon.com
      PLEX_CLAIM: claim-Bq3vvnCtrkF-HzxTii-H
      PLEX_UID: 1000
      PLEX_GID: 1000
    expose:
      - "32400"
      - "33400"
        #    ports:
        #      - "32400:32400"
        #      - "33400:33400"
    volumes:
      - /srv/tvshow:/data/
#      - /rapidStorage/PlexConfig/:/config
#      - /tmp:/transcode
    networks:
      - dmz
# TODO change devices
# when gpu import is implemented
#    devices:
#      - "/dev/dri/card0:/dev/dri/card0"
#      - "/dev/dri/renderD128:/dev/dri/renderD128"

networks:
  dmz:
    external: true
