version: '3.5'

services:

    portainer:
        image: portainer/portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /srv/portainer/data:/data