version: '3'

services:

    jackett:
       container_name: jackett
       image: linuxserver/jackett:latest
       restart: always
       environment:
           - PGID=1000
           - PUID=1000
           - TZ=Europe/London
       volumes:
           - /srv/jackett/config:/config
           - /srv/jackett/downloads:/downloads
       ports:
         - "9117:9117"