version: '3.5'
services:
    emby:
        # 12/06/2019
        image: emby/embyserver:4.2.0.15
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /srv/emby/config:/config
            - /srv/tvshow:/media/tvshow
            - /srv/movie:/media/movie
        environment:
            - VIRTUAL_PORT=8096
            - VIRTUAL_HOST=emby.htpc
            - AUTO_UPDATES_ON=true
            - APP_UID=1000
            - APP_GID=1000
        networks:
            - dmz
        deploy:
            mode: replicated
            replicas: 1

    plex:
        image: plexinc/pms-docker
        environment:
            - TZ=Europe/Paris
            - ADVERTISE_IP=https://plex.vincentriouallon.com
            - PLEX_CLAIM=claim-CuEbqKWY4akeV7zsuh7p
            - PLEX_UID=1000
            - PLEX_GID=1000
        ports:
            - "32400:32400"
        volumes:
            - /srv/tvshow:/data/tvshow
            - /srv/movie:/data/movie
            - /srv/plex/config/:/config
            # - /tmp:/transcode
        networks:
            - dmz
        deploy:
            mode: replicated
            replicas: 1
    # TODO change devices
    # when gpu import is implemented
    #    devices:
    #      - "/dev/dri/card0:/dev/dri/card0"
    #      - "/dev/dri/renderD128:/dev/dri/renderD128"



networks:
    dmz:
        external: true

    plex:
        driver: overlay
        attachable: true

