version: '3.5'

services:
    sonarr:
        # 12/06/2019
        image: linuxserver/sonarr:3.0.1.520-ls91
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /dev/rtc:/dev/rtc:ro
          - /srv/sonarr/config:/config
          - /srv/deluge/downloads:/downloads
          - /srv/tvshow:/tv
        networks:
            - dmz
        deploy:
            mode: replicated
            replicas: 1

networks:
    dmz:
        external: true