version: '3.5'

services:

    sonarr:
        # 12/06/2019
        image: linuxserver/sonarr:2.0.0.5322-ls19
        ports:
          - 8989:8989
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /dev/rtc:/dev/rtc:ro
          - /srv/sonarr/config:/config
          - /srv/deluge/downloads:/downloads
          - /srv/tvshow:/tv
        links:
            - deluge
        depends_on:
            - deluge