---
- debug:
    msg: "{{ hostvars[inventory_hostname] }}"
    
- name: Dependencies installation
  pacman:
    name:
      - git
      - vim
      - htop
      - zsh
    update_cache: yes
    # upgrade: yes
    state: latest
...