---

- name: Determine SSH port used
  remote_user: root
  tasks:
    - name: "Check port {{ ansible_port }}"
      wait_for:
        port: "{{ ansible_port }}"
        state: "started"
        host: "{{ inventory_hostname }}"
        connect_timeout: "5"
        timeout: "5"
      delegate_to: "localhost"
      ignore_errors: "yes"
      register: ssh_port_used

- debug:
    msg: "{{ ssh_port_used }}"

- name: Security | Disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^[#]*PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: restart ssh
  tags: ["ssh"]
...