---

- name: install Docker and dependencies
  pacman:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  with_items: "{{ packages}}"

# - name: Add  user to docker group
#   user:
#     name: "{{ ansible_user }}"
#     group: "{{ docker_group }}"

# - name: Create docker service directory
#   file:
#     path: /etc/systemd/system/docker.service.d
#     state: directory
#   notify:
#     - restart docker

- name: Ensure Docker is running
  service:
    name: docker
    state: started
    enabled: yes
...