version: '3'

services:

    portainer:
        container_name: portainer
        image: portainer/portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /srv/portainer/data:/data