- name: Server installation
  hosts: seedbox
  remote_user: root

  tasks:
    - name: Dependencies installation
      pacman:
        name:
          - git
          - vim
          - htop
          - zsh
        update_cache: yes
